// packages-import/markets-ui/apps/angular-reference-app/src/app/views/view1.component.ts
/**
 * View1Component — sample view with FDC3 context broadcasting.
 * Angular equivalent of the React View1.
 */

import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-view1',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="flex flex-col gap-4 p-4">
      <h1 class="text-lg font-bold">Angular View 1</h1>
      <p class="text-sm text-muted-foreground">
        This is a sample OpenFin view rendered by Angular.
        It demonstrates how an Angular component can run inside an OpenFin view.
      </p>
      <button
        class="px-4 py-2 text-sm font-medium rounded border cursor-pointer
               bg-primary text-primary-foreground hover:opacity-90"
        (click)="broadcastContext()"
      >
        Broadcast FDC3 Context
      </button>
      <p class="text-xs text-muted-foreground">{{ status }}</p>
    </div>
  `,
})
export class View1Component {
  status = '';

  async broadcastContext(): Promise<void> {
    try {
      const fdc3 = (window as any).fdc3;
      if (fdc3) {
        await fdc3.broadcast({
          type: 'fdc3.instrument',
          name: 'Apple',
          id: { ticker: 'AAPL' },
        });
        this.status = 'Context broadcast: AAPL';
      } else {
        this.status = 'FDC3 API not available';
      }
    } catch (err) {
      this.status = 'Broadcast failed';
      console.error(err);
    }
  }
}

// packages-import/markets-ui/apps/container/src/views/View1.tsx
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../components/ui/card";

function View1() {
  async function broadcastFDC3Context() {
    if (window.fdc3) {
      await fdc3.broadcast({
        type: "fdc3.instrument",
        name: "Microsoft Corporation",
        id: {
          ticker: "MSFT",
        },
      });
    } else {
      console.error("FDC3 is not available");
    }
  }

  async function broadcastFDC3ContextAppChannel() {
    if (window.fdc3) {
      const appChannel = await fdc3.getOrCreateChannel("CUSTOM-APP-CHANNEL");
      await appChannel.broadcast({
        type: "fdc3.instrument",
        name: "Apple Inc.",
        id: {
          ticker: "AAPL",
        },
      });
    } else {
      console.error("FDC3 is not available");
    }
  }

  return (
    <div className="flex flex-col flex-1 gap-5">
      <header className="flex flex-row justify-between items-center">
        <div className="flex flex-col">
          <h1 className="text-xl font-bold">OpenFin React View 1</h1>
          <p className="text-sm text-muted-foreground">React app view in an OpenFin container</p>
        </div>
      </header>
      <main>
        <Card>
          <CardHeader>
            <CardTitle>FDC3 Broadcasting</CardTitle>
            <CardDescription>Broadcast instrument context to other views</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-2">
            <Button onClick={() => broadcastFDC3Context()}>Broadcast FDC3 User Context</Button>
            <Button variant="secondary" onClick={() => broadcastFDC3ContextAppChannel()}>
              Broadcast FDC3 App Context
            </Button>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}

export default View1;
