// packages-import/markets-ui/packages/react-tools/dock-editor/src/components/dock-editor/TreeItem.tsx
import { useState } from "react";
import { DynamicIcon as Icon } from "@markets/icons-svg/react";

export interface TreeItemData {
  id: string;
  label: string;
  iconId: string;
  iconName: string;
  actionId?: string;
  childCount?: number;
  children?: TreeItemData[];
  /** True if this item is a container (dropdown/submenu) even when children is empty */
  isContainer?: boolean;
}

interface TreeItemProps {
  item: TreeItemData;
  index: number;
  total: number;
  depth: number;
  onEdit: (id: string) => void;
  onRemove: (id: string) => void;
  onMoveUp: (id: string) => void;
  onMoveDown: (id: string) => void;
  onAddChild: (parentId: string) => void;
  children?: React.ReactNode;
}

// Pixels of horizontal indentation per nesting level.
// Update this one constant to change indentation for the entire tree.
const INDENT_STEP = 22;

export function TreeItem({ item, index, total, depth, onEdit, onRemove, onMoveUp, onMoveDown, onAddChild, children: childNodes }: TreeItemProps) {
  const [expanded, setExpanded] = useState(true);
  const [hovered, setHovered] = useState(false);

  // An item "has children" if it is a container type (dropdown/submenu)
  // OR if child data was provided. Both cases show the expand toggle.
  const hasChildren = item.isContainer || (item.childCount ?? 0) > 0 || (item.children && item.children.length > 0);

  return (
    <div style={{ position: "relative" }}>
      {/* Indent guide */}
      {depth > 0 && (
        <div style={{
          position: "absolute", left: depth * INDENT_STEP + 6, top: 0, bottom: 0,
          width: 1, background: "var(--de-border)",
        }} />
      )}

      {/* Row */}
      <div
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
        style={{
          display: "flex", alignItems: "center", gap: 4,
          paddingLeft: depth * INDENT_STEP + 8, paddingRight: 6, height: 32,
          borderRadius: "var(--de-radius-sm)", marginBottom: 1,
          background: hovered ? "var(--de-bg-hover)" : "transparent",
          transition: "background 0.12s ease",
        }}
      >
        {/* Expand toggle */}
        {hasChildren ? (
          <button onClick={() => setExpanded(!expanded)} style={{
            width: 20, height: 20, display: "flex", alignItems: "center", justifyContent: "center",
            border: "none", background: "none", cursor: "pointer", color: "var(--de-text-tertiary)",
            borderRadius: 4, padding: 0, flexShrink: 0, transition: "color 0.1s",
          }} onMouseEnter={e => { e.currentTarget.style.color = "var(--de-text)"; }}
             onMouseLeave={e => { e.currentTarget.style.color = "var(--de-text-tertiary)"; }}>
            <Icon icon={expanded ? "lucide:chevron-down" : "lucide:chevron-right"} style={{ width: 13, height: 13 }} />
          </button>
        ) : <span style={{ width: 20, flexShrink: 0 }} />}

        {/* Drag handle */}
        <span style={{ width: 12, display: "flex", alignItems: "center", justifyContent: "center", color: "var(--de-text-ghost)", cursor: "grab", flexShrink: 0 }}>
          <Icon icon="lucide:grip-vertical" style={{ width: 12, height: 12 }} />
        </span>

        {/* Icon chip */}
        <span style={{
          width: 24, height: 24, display: "flex", alignItems: "center", justifyContent: "center",
          borderRadius: 5, background: "var(--de-bg-surface)", flexShrink: 0,
          border: "1px solid var(--de-border-subtle)",
        }}>
          <Icon icon={item.iconId} style={{ width: 13, height: 13, color: "var(--de-text-secondary)" }} />
        </span>

        {/* Label */}
        <span style={{
          flex: 1, fontSize: 13, fontWeight: 500, color: "var(--de-text)",
          overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap",
          paddingLeft: 4, fontFamily: "var(--de-font)",
        }}>
          {item.label}
        </span>

        {/* Child count */}
        {hasChildren && (
          <span style={{
            minWidth: 20, height: 18, display: "flex", alignItems: "center", justifyContent: "center",
            borderRadius: 9, background: "var(--de-bg-surface)", border: "1px solid var(--de-border-subtle)",
            fontSize: 10, fontWeight: 600, color: "var(--de-text-tertiary)",
            paddingLeft: 5, paddingRight: 5, flexShrink: 0,
          }}>
            {item.childCount ?? item.children?.length ?? 0}
          </span>
        )}

        {/* Actions */}
        <div style={{
          display: "flex", alignItems: "center", gap: 1, flexShrink: 0,
          opacity: hovered ? 1 : 0, transition: "opacity 0.12s ease",
        }}>
          <ActionBtn icon="lucide:chevron-up" onClick={() => onMoveUp(item.id)} disabled={index === 0} title="Move up" />
          <ActionBtn icon="lucide:chevron-down" onClick={() => onMoveDown(item.id)} disabled={index === total - 1} title="Move down" />
          <ActionBtn icon="lucide:pencil" onClick={() => onEdit(item.id)} title="Edit" />
          <ActionBtn icon="lucide:trash-2" onClick={() => onRemove(item.id)} title="Delete" danger />
        </div>
      </div>

      {/* Children */}
      {hasChildren && expanded && childNodes}

      {/* Add child */}
      {hasChildren && expanded && (
        <button onClick={() => onAddChild(item.id)} style={{
          display: "flex", alignItems: "center", gap: 5,
          paddingLeft: (depth + 1) * INDENT_STEP + 32, paddingRight: 8, height: 26,
          border: "none", background: "none", color: "var(--de-text-ghost)",
          fontSize: 11, fontFamily: "var(--de-font)", fontWeight: 500,
          cursor: "pointer", borderRadius: "var(--de-radius-sm)", transition: "all 0.12s",
        }} onMouseEnter={e => { e.currentTarget.style.color = "var(--de-accent)"; e.currentTarget.style.background = "var(--de-accent-subtle)"; }}
           onMouseLeave={e => { e.currentTarget.style.color = "var(--de-text-ghost)"; e.currentTarget.style.background = "none"; }}>
          <Icon icon="lucide:plus" style={{ width: 11, height: 11 }} />
          Add child
        </button>
      )}
    </div>
  );
}

// ── Tiny action button ───────────────────────────────────────────────

function ActionBtn({ icon, onClick, disabled, title, danger }: {
  icon: string; onClick: () => void; disabled?: boolean; title: string; danger?: boolean;
}) {
  return (
    <button onClick={onClick} disabled={disabled} title={title} style={{
      width: 26, height: 26, display: "flex", alignItems: "center", justifyContent: "center",
      border: "none", borderRadius: 4, cursor: disabled ? "default" : "pointer",
      background: "none", padding: 0, transition: "all 0.1s",
      color: disabled ? "var(--de-text-ghost)" : danger ? "var(--de-danger)" : "var(--de-text-secondary)",
      opacity: disabled ? 0.35 : 1,
    }} onMouseEnter={e => {
      if (!disabled) {
        e.currentTarget.style.background = danger ? "var(--de-danger-dim)" : "var(--de-bg-active)";
        e.currentTarget.style.color = danger ? "var(--de-danger)" : "var(--de-text)";
      }
    }}
       onMouseLeave={e => {
         e.currentTarget.style.background = "none";
         e.currentTarget.style.color = disabled ? "var(--de-text-ghost)" : danger ? "var(--de-danger)" : "var(--de-text-secondary)";
       }}>
      <Icon icon={icon} style={{ width: 14, height: 14 }} />
    </button>
  );
}

// packages-import/markets-ui/packages/angular-tools/dock-editor/src/dock-editor/tree-item/tree-item.component.ts
/**
 * TreeItemComponent
 *
 * Renders a single row in the dock editor's button tree.
 * Uses PrimeNG Button + Tailwind CSS for layout and styling.
 * Dynamic indent uses [style.paddingLeft.px] since depth is runtime-calculated.
 */

import {
  Component,
  Input,
  Output,
  EventEmitter,
  signal,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { ButtonModule } from 'primeng/button';
import { TooltipModule } from 'primeng/tooltip';
import { BadgeModule } from 'primeng/badge';
import { iconIdToSvgUrl } from '../icon-utils';

const INDENT_STEP = 22;

export interface TreeItemData {
  id: string;
  label: string;
  iconId: string;
  iconUrl?: string;
  actionId?: string;
  childCount?: number;
  children?: TreeItemData[];
  isContainer?: boolean;
}

@Component({
  selector: 'mkt-tree-item',
  standalone: true,
  imports: [CommonModule, ButtonModule, TooltipModule, BadgeModule],
  template: `
    <!-- Indent guide -->
    <div
      *ngIf="depth > 0"
      class="absolute top-0 bottom-0 w-px bg-border"
      [style.left.px]="depth * INDENT_STEP + 6"
    ></div>

    <!-- Row -->
    <div
      (mouseenter)="hovered.set(true)"
      (mouseleave)="hovered.set(false)"
      class="flex items-center gap-1 pr-1.5 h-8 rounded mb-px transition-colors"
      [class.bg-muted]="hovered()"
      [style.paddingLeft.px]="depth * INDENT_STEP + 8"
    >
      <!-- Expand/collapse toggle -->
      <button
        *ngIf="hasChildren; else spacer"
        (click)="expanded.set(!expanded())"
        class="w-5 h-5 flex items-center justify-center border-none bg-transparent
               cursor-pointer text-muted-foreground rounded p-0 flex-shrink-0"
      >
        <img
          [src]="expanded() ? chevronDownUrl : chevronRightUrl"
          width="13" height="13" alt=""
        />
      </button>
      <ng-template #spacer>
        <span class="w-5 flex-shrink-0"></span>
      </ng-template>

      <!-- Drag handle -->
      <span class="w-3 flex items-center justify-center text-muted-foreground cursor-grab flex-shrink-0">
        <img [src]="gripUrl" width="12" height="12" alt="" />
      </span>

      <!-- Icon chip -->
      <span class="w-6 h-6 flex items-center justify-center rounded bg-card border border-border flex-shrink-0">
        <img [src]="getItemIconUrl()" width="13" height="13" [alt]="item.label" />
      </span>

      <!-- Label -->
      <span class="flex-1 text-sm font-medium text-foreground overflow-hidden text-ellipsis whitespace-nowrap pl-1">
        {{ item.label }}
      </span>

      <!-- Child count badge -->
      <span
        *ngIf="hasChildren"
        class="min-w-[20px] h-[18px] flex items-center justify-center rounded-full
               bg-card border border-border text-[10px] font-semibold text-muted-foreground
               px-1.5 flex-shrink-0"
      >
        {{ item.childCount ?? item.children?.length ?? 0 }}
      </span>

      <!-- Action buttons (visible on hover) -->
      <div
        class="flex items-center gap-px flex-shrink-0 transition-opacity"
        [class.opacity-0]="!hovered()"
        [class.opacity-100]="hovered()"
      >
        <p-button
          [text]="true"
          [rounded]="true"
          size="small"
          [disabled]="isFirst"
          (onClick)="moveUp.emit(item.id)"
          pTooltip="Move up"
          tooltipPosition="top"
        >
          <img [src]="chevronUpUrl" width="14" height="14" alt="up" />
        </p-button>
        <p-button
          [text]="true"
          [rounded]="true"
          size="small"
          [disabled]="isLast"
          (onClick)="moveDown.emit(item.id)"
          pTooltip="Move down"
          tooltipPosition="top"
        >
          <img [src]="chevronDownUrl" width="14" height="14" alt="down" />
        </p-button>
        <p-button
          [text]="true"
          [rounded]="true"
          size="small"
          (onClick)="edit.emit(item.id)"
          pTooltip="Edit"
          tooltipPosition="top"
        >
          <img [src]="pencilUrl" width="14" height="14" alt="edit" />
        </p-button>
        <p-button
          [text]="true"
          [rounded]="true"
          size="small"
          severity="danger"
          (onClick)="remove.emit(item.id)"
          pTooltip="Delete"
          tooltipPosition="top"
        >
          <img [src]="trashUrl" width="14" height="14" alt="delete" />
        </p-button>
      </div>
    </div>

    <!-- Children -->
    <ng-container *ngIf="hasChildren && expanded()">
      <mkt-tree-item
        *ngFor="let child of item.children; let i = index"
        [item]="child"
        [index]="i"
        [total]="item.children?.length ?? 0"
        [depth]="depth + 1"
        [theme]="theme"
        (edit)="edit.emit($event)"
        (remove)="remove.emit($event)"
        (moveUp)="moveUp.emit($event)"
        (moveDown)="moveDown.emit($event)"
        (addChild)="addChild.emit($event)"
      />
      <button
        (click)="addChild.emit(item.id)"
        class="flex items-center gap-1.5 pr-2 h-[26px] border-none bg-transparent
               text-muted-foreground text-xs font-medium cursor-pointer rounded"
        [style.paddingLeft.px]="(depth + 1) * INDENT_STEP + 32"
      >
        <img [src]="plusUrl" width="11" height="11" alt="" />
        Add child
      </button>
    </ng-container>
  `,
  styles: [`
    :host { display: block; position: relative; }
  `],
})
export class TreeItemComponent {
  @Input({ required: true }) item!: TreeItemData;
  @Input() index = 0;
  @Input() total = 1;
  @Input() depth = 0;
  @Input() theme: 'dark' | 'light' = 'dark';

  @Output() edit     = new EventEmitter<string>();
  @Output() remove   = new EventEmitter<string>();
  @Output() moveUp   = new EventEmitter<string>();
  @Output() moveDown = new EventEmitter<string>();
  @Output() addChild = new EventEmitter<string>();

  protected readonly expanded = signal(true);
  protected readonly hovered  = signal(false);
  protected readonly INDENT_STEP = INDENT_STEP;

  // Chrome icon colors per theme
  private get secondaryColor(): string { return this.theme === 'dark' ? '#8b8b9e' : '#5c5c72'; }
  private get tertiaryColor(): string { return this.theme === 'dark' ? '#5c5c6e' : '#8e8ea0'; }
  private get ghostColor(): string { return this.theme === 'dark' ? '#3a3a4a' : '#b8b8c8'; }

  protected get chevronDownUrl(): string  { return iconIdToSvgUrl('lucide:chevron-down',  this.tertiaryColor); }
  protected get chevronRightUrl(): string { return iconIdToSvgUrl('lucide:chevron-right', this.tertiaryColor); }
  protected get chevronUpUrl(): string    { return iconIdToSvgUrl('lucide:chevron-up',    this.secondaryColor); }
  protected get gripUrl(): string         { return iconIdToSvgUrl('lucide:grip-vertical', this.ghostColor); }
  protected get pencilUrl(): string       { return iconIdToSvgUrl('lucide:pencil',        this.secondaryColor); }
  protected get trashUrl(): string        { return iconIdToSvgUrl('lucide:trash-2',       '#e5534b'); }
  protected get plusUrl(): string          { return iconIdToSvgUrl('lucide:plus',           this.ghostColor); }

  get hasChildren(): boolean {
    return !!this.item.isContainer || (this.item.childCount ?? 0) > 0 || (this.item.children?.length ?? 0) > 0;
  }
  get isFirst(): boolean { return this.index === 0; }
  get isLast():  boolean { return this.index === this.total - 1; }

  protected getItemIconUrl(): string {
    return iconIdToSvgUrl(this.item.iconId, this.secondaryColor);
  }
}
