// packages-import/fi-trading-terminal/angular-app/src/app/app.ts
import { Component, signal, effect, PLATFORM_ID, inject, Type } from '@angular/core';
import { isPlatformBrowser, CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DockManagerCoreComponent, type DockTheme } from '@widgetstools/angular-dock-manager';
import {
  type DockManagerState,
  type DockviewApi,
  slateDark,
  vsCodeLight,
} from '@widgetstools/dock-manager-core';
import { TICKER_STRIP, type TickerItem } from './services/trading-data.service';
import { SharedStateService } from './services/shared-state.service';

// Widget imports
import { BondBlotterWidget } from './widgets/bond-blotter.widget';
import { ChartWidget } from './widgets/chart.widget';
import { OrderBookWidget } from './widgets/order-book.widget';
import { OrdersPanelWidget } from './widgets/orders-panel.widget';
import { TradeTicketWidget } from './widgets/trade-ticket.widget';
import { RfqWidget } from './widgets/rfq.widget';
import { RiskKpiWidget } from './widgets/risk-kpi.widget';
import { BookRiskWidget } from './widgets/book-risk.widget';
import { Dv01ChartWidget } from './widgets/dv01-chart.widget';
import { ScenarioChartWidget } from './widgets/scenario-chart.widget';
import { VarTrendWidget } from './widgets/var-trend.widget';
import { RiskLimitsWidget } from './widgets/risk-limits.widget';
import { MarketIndicesWidget } from './widgets/market-indices.widget';
import { EconCalendarWidget } from './widgets/econ-calendar.widget';
import { IntradayChartWidget } from './widgets/intraday-chart.widget';
import { YieldCurveWidget } from './widgets/yield-curve.widget';
import { OrderKpiWidget } from './widgets/order-kpi.widget';
import { OrderBlotterWidget } from './widgets/order-blotter.widget';
import { OrderDetailWidget } from './widgets/order-detail.widget';
import { OasDurationWidget } from './widgets/oas-duration.widget';
import { DurationBucketsWidget } from './widgets/duration-buckets.widget';
import { SectorAllocationWidget } from './widgets/sector-allocation.widget';
import { HistoricalOasWidget } from './widgets/historical-oas.widget';
import { OasDistributionWidget } from './widgets/oas-distribution.widget';
import { PnlAttributionWidget } from './widgets/pnl-attribution.widget';
import { ResearchListWidget } from './widgets/research-list.widget';
import { NoteDetailWidget } from './widgets/note-detail.widget';
import { DesignSystemWidget } from './widgets/design-system.widget';

// ── Widget registry ──
const WIDGETS: Record<string, Type<any>> = {
  chart: ChartWidget,
  orderBook: OrderBookWidget,
  tradeTicket: TradeTicketWidget,
  blotter: OrdersPanelWidget,
  rfq: RfqWidget,
  bondBlotter: BondBlotterWidget,
  riskKpi: RiskKpiWidget,
  bookRisk: BookRiskWidget,
  dv01: Dv01ChartWidget,
  scenario: ScenarioChartWidget,
  varTrend: VarTrendWidget,
  riskLimits: RiskLimitsWidget,
  indices: MarketIndicesWidget,
  econCal: EconCalendarWidget,
  intraday: IntradayChartWidget,
  yieldCurve: YieldCurveWidget,
  orderKpi: OrderKpiWidget,
  orderBlotter: OrderBlotterWidget,
  orderDetail: OrderDetailWidget,
  oasDur: OasDurationWidget,
  durBuckets: DurationBucketsWidget,
  sectors: SectorAllocationWidget,
  histOas: HistoricalOasWidget,
  oasDist: OasDistributionWidget,
  pnl: PnlAttributionWidget,
  researchList: ResearchListWidget,
  noteDetail: NoteDetailWidget,
  designSystem: DesignSystemWidget,
};

// ── Layout helpers ──
const p = (id: string, title: string, wt: string, closable = false) => ({
  id,
  title,
  widgetType: wt,
  closable,
});
const tg = (id: string, panels: string[], active?: string) => ({
  type: 'tabgroup' as const,
  id,
  panels,
  activePanel: active || panels[0],
});
const sp = (id: string, dir: 'horizontal' | 'vertical', sizes: number[], children: any[]) => ({
  type: 'split' as const,
  id,
  direction: dir,
  sizes,
  children,
});
const base = (layout: any, panels: Record<string, any>, active: string): DockManagerState => ({
  layout,
  panels,
  floatingPanels: [],
  popoutPanels: [],
  unpinnedPanels: [],
  nextZIndex: 100,
  activePaneId: active,
});

// ── Per-tab layouts (identical to React) ──
function tradeLayout(): DockManagerState {
  return base(
    sp(
      'root',
      'vertical',
      [55, 45],
      [
        sp(
          'top',
          'horizontal',
          [32, 68],
          [tg('tg-blotter', ['bondBlotter']), tg('tg-chart', ['chart'])],
        ),
        sp(
          'bottom',
          'horizontal',
          [32, 68],
          [tg('tg-ob', ['orderBook']), tg('tg-orders', ['blotter'])],
        ),
      ],
    ),
    {
      bondBlotter: p('bondBlotter', 'Bond Blotter', 'bondBlotter'),
      chart: p('chart', 'Chart', 'chart'),
      orderBook: p('orderBook', 'Order Book', 'orderBook'),
      blotter: p('blotter', 'Orders', 'blotter'),
    },
    'bondBlotter',
  );
}
function pricesLayout(): DockManagerState {
  return base(
    sp(
      'root',
      'vertical',
      [65, 35],
      [
        tg('tg-blotter', ['bondBlotter']),
        sp(
          'bottom',
          'horizontal',
          [60, 40],
          [tg('tg-chart', ['chart']), tg('tg-ob', ['orderBook'])],
        ),
      ],
    ),
    {
      bondBlotter: p('bondBlotter', 'Bond Blotter', 'bondBlotter'),
      chart: p('chart', 'Chart', 'chart'),
      orderBook: p('orderBook', 'Order Book', 'orderBook'),
    },
    'bondBlotter',
  );
}
function riskLayout(): DockManagerState {
  return base(
    sp(
      'root',
      'vertical',
      [12, 88],
      [
        tg('tg-kpi', ['riskKpi']),
        sp(
          'body',
          'horizontal',
          [25, 50, 25],
          [
            tg('tg-book', ['bookRisk']),
            sp(
              'charts',
              'vertical',
              [50, 50],
              [
                sp(
                  'charts-top',
                  'horizontal',
                  [50, 50],
                  [tg('tg-dv01', ['dv01']), tg('tg-scenario', ['scenario'])],
                ),
                tg('tg-var', ['varTrend']),
              ],
            ),
            tg('tg-limits', ['riskLimits']),
          ],
        ),
      ],
    ),
    {
      riskKpi: p('riskKpi', 'Risk KPIs', 'riskKpi'),
      bookRisk: p('bookRisk', 'Book Risk & Heatmap', 'bookRisk'),
      dv01: p('dv01', 'DV01 by Book', 'dv01'),
      scenario: p('scenario', 'Rate Scenarios', 'scenario'),
      varTrend: p('varTrend', 'VaR Trend', 'varTrend'),
      riskLimits: p('riskLimits', 'Risk Limits', 'riskLimits'),
    },
    'riskKpi',
  );
}
function marketLayout(): DockManagerState {
  return base(
    sp(
      'root',
      'horizontal',
      [30, 70],
      [
        sp('left', 'vertical', [60, 40], [tg('tg-idx', ['indices']), tg('tg-cal', ['econCal'])]),
        sp(
          'right',
          'vertical',
          [55, 45],
          [tg('tg-intra', ['intraday']), tg('tg-yc', ['yieldCurve'])],
        ),
      ],
    ),
    {
      indices: p('indices', 'Market Indices', 'indices'),
      econCal: p('econCal', 'Economic Calendar', 'econCal'),
      intraday: p('intraday', 'Intraday Chart', 'intraday'),
      yieldCurve: p('yieldCurve', 'Yield Curve', 'yieldCurve'),
    },
    'indices',
  );
}
function ordersLayout(): DockManagerState {
  return base(
    sp(
      'root',
      'vertical',
      [12, 88],
      [
        tg('tg-kpi', ['orderKpi']),
        sp(
          'body',
          'horizontal',
          [75, 25],
          [tg('tg-blot', ['orderBlotter']), tg('tg-det', ['orderDetail'])],
        ),
      ],
    ),
    {
      orderKpi: p('orderKpi', 'Order KPIs', 'orderKpi'),
      orderBlotter: p('orderBlotter', 'Order Blotter', 'orderBlotter'),
      orderDetail: p('orderDetail', 'Order Detail', 'orderDetail'),
    },
    'orderBlotter',
  );
}
function analyticsLayout(): DockManagerState {
  return base(
    sp(
      'root',
      'vertical',
      [50, 50],
      [
        sp(
          'row1',
          'horizontal',
          [34, 33, 33],
          [tg('tg-oas', ['oasDur']), tg('tg-dur', ['durBuckets']), tg('tg-sec', ['sectors'])],
        ),
        sp(
          'row2',
          'horizontal',
          [34, 33, 33],
          [tg('tg-hist', ['histOas']), tg('tg-dist', ['oasDist']), tg('tg-pnl', ['pnl'])],
        ),
      ],
    ),
    {
      oasDur: p('oasDur', 'OAS vs Duration', 'oasDur'),
      durBuckets: p('durBuckets', 'Duration Buckets', 'durBuckets'),
      sectors: p('sectors', 'Sector Allocation', 'sectors'),
      histOas: p('histOas', 'CDX IG/HY Historical', 'histOas'),
      oasDist: p('oasDist', 'OAS Distribution', 'oasDist'),
      pnl: p('pnl', 'P&L Attribution', 'pnl'),
    },
    'oasDur',
  );
}
function researchLayout(): DockManagerState {
  return base(
    sp(
      'root',
      'horizontal',
      [30, 70],
      [tg('tg-list', ['researchList']), tg('tg-detail', ['noteDetail'])],
    ),
    {
      researchList: p('researchList', 'Research Notes', 'researchList'),
      noteDetail: p('noteDetail', 'Note Detail', 'noteDetail'),
    },
    'researchList',
  );
}

function designSystemLayout(): DockManagerState {
  return base(
    tg('tg-ds', ['designSystem']),
    {
      designSystem: p('designSystem', 'Design System', 'designSystem'),
    },
    'designSystem',
  );
}

const TAB_LAYOUTS: Record<string, () => DockManagerState> = {
  Trade: tradeLayout,
  Prices: pricesLayout,
  Risk: riskLayout,
  Market: marketLayout,
  Research: researchLayout,
  Orders: ordersLayout,
  Analytics: analyticsLayout,
  'Design System': designSystemLayout,
};

const NAV_TABS = [
  'Prices',
  'Trade',
  'Risk',
  'Market',
  'Research',
  'Orders',
  'Analytics',
  'Design System',
];

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule, DockManagerCoreComponent],
  template: `
    <!-- Top Bar -->
    <div style="flex-shrink:0;background:var(--bn-bg1);border-bottom:1px solid var(--bn-border)">
      <!-- Main nav bar -->
      <div
        style="display:flex;align-items:center;height:44px;padding:0 16px;gap:0;border-bottom:1px solid var(--bn-border)"
      >
        <!-- Logo -->
        <div style="display:flex;align-items:center;gap:8px;margin-right:24px;flex-shrink:0">
          <svg width="22" height="22" viewBox="0 0 22 22" fill="none">
            <rect width="22" height="22" rx="4" fill="var(--bn-yellow)" />
            <path
              d="M11 4l2.5 2.5L11 9 8.5 6.5 11 4zM4 11l2.5-2.5L9 11l-2.5 2.5L4 11zM11 18l-2.5-2.5L11 13l2.5 2.5L11 18zM18 11l-2.5 2.5L13 11l2.5-2.5L18 11zM11 9.5L12.5 11 11 12.5 9.5 11 11 9.5z"
              fill="var(--bn-logo-bg)"
            />
          </svg>
          <span style="font-weight:700;font-size:13px;letter-spacing:0.04em;color:var(--bn-t0)"
            >MarketsUI <span style="color:var(--bn-yellow)">FI</span></span
          >
        </div>
        <!-- Nav tabs -->
        <button
          *ngFor="let t of navTabs"
          (click)="setActiveTab(t)"
          class="bn-tab"
          [class.active]="activeTab() === t"
        >
          {{ t }}
        </button>
        <!-- Right side -->
        <div style="margin-left:auto;display:flex;align-items:center;gap:10px">
          <ng-container *ngIf="isTrading">
            <button
              (click)="handleNewOrder()"
              style="font-size:11px;padding:4px 12px;border-radius:3px;background:var(--bn-bg3);color:var(--bn-t0);cursor:pointer;border:1px solid var(--bn-border2);white-space:nowrap;font-family:JetBrains Mono,monospace;font-weight:600"
            >
              + New Order
            </button>
            <button
              (click)="handleOpenRfq()"
              style="font-size:11px;padding:4px 12px;border-radius:3px;background:var(--bn-bg3);color:var(--bn-t0);cursor:pointer;border:1px solid var(--bn-border2);white-space:nowrap;font-family:JetBrains Mono,monospace;font-weight:600"
            >
              RFQ
            </button>
            <div style="width:1px;height:14px;background:var(--bn-border);flex-shrink:0"></div>
          </ng-container>
          <!-- LIVE indicator -->
          <div style="display:flex;align-items:center;gap:6px">
            <div
              class="live-dot"
              style="width:6px;height:6px;border-radius:50%;background:var(--bn-green)"
            ></div>
            <span class="font-mono-fi" style="color:var(--bn-green);font-size:11px">LIVE</span>
          </div>
          <div style="width:1px;height:14px;background:var(--bn-border);flex-shrink:0"></div>
          <!-- Clock -->
          <span class="font-mono-fi" style="color:var(--bn-t1);font-size:11px">{{ time }}</span>
          <div style="width:1px;height:14px;background:var(--bn-border);flex-shrink:0"></div>
          <!-- Theme toggle -->
          <button
            (click)="toggleTheme()"
            style="display:flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:4px;background:var(--bn-bg3);color:var(--bn-t1);border:none;cursor:pointer;font-size:13px"
            [title]="isDark() ? 'Switch to light mode' : 'Switch to dark mode'"
          >
            {{ isDark() ? '☀' : '☽' }}
          </button>
        </div>
      </div>

      <!-- Instrument stats strip (Trade/Prices tabs) -->
      <div
        *ngIf="isTrading"
        style="display:flex;align-items:center;height:36px;border-bottom:1px solid var(--bn-border);padding:0 16px;gap:16px"
      >
        <div
          *ngFor="let s of statsStrip; let i = index; let last = last"
          style="display:flex;align-items:center;flex-shrink:0;gap:5px"
          [style.paddingRight.px]="last ? 0 : 12"
          [style.borderRight]="last ? 'none' : '1px solid var(--bn-border)'"
          [style.width.px]="s.w"
        >
          <span style="font-size:9px;color:var(--bn-t2);white-space:nowrap;flex-shrink:0">{{
            s.label
          }}</span>
          <span
            class="font-mono-fi font-semibold"
            style="font-size:11px;white-space:nowrap;font-variant-numeric:tabular-nums"
            [style.color]="s.color"
            >{{ s.val }}</span
          >
        </div>
        <div style="width:1px;height:18px;background:var(--bn-border);flex-shrink:0"></div>
        <!-- Ticker strip (compact, right side) -->
        <div style="display:flex;align-items:center;overflow:hidden;gap:4px;margin-left:auto">
          <div
            *ngFor="let t of tickerStrip.slice(0, 8)"
            style="display:flex;align-items:center;padding:3px 7px;border-radius:3px;gap:5px;background:var(--bn-bg2);flex-shrink:0"
          >
            <span style="font-size:9px;color:var(--bn-t2);white-space:nowrap">{{ t.label }}</span>
            <span
              class="font-mono-fi font-semibold"
              style="font-size:11px;color:var(--bn-t0);white-space:nowrap"
              >{{ t.value }}</span
            >
            <span
              class="font-mono-fi"
              style="font-size:9px;white-space:nowrap"
              [style.color]="t.up ? 'var(--bn-green)' : 'var(--bn-red)'"
              >{{ t.change }}</span
            >
          </div>
        </div>
      </div>

      <!-- Ticker strip only (non-trade tabs) -->
      <div
        *ngIf="!isTrading"
        style="display:flex;align-items:stretch;overflow:hidden;height:38px;border-bottom:1px solid var(--bn-border)"
      >
        <div
          *ngFor="let t of tickerStrip"
          style="display:flex;align-items:center;gap:8px;padding:0 12px;border-right:1px solid var(--bn-border)"
        >
          <span style="font-size:11px;color:var(--bn-t2);white-space:nowrap">{{ t.label }}</span>
          <span
            class="font-mono-fi font-semibold"
            style="font-size:11px;color:var(--bn-t0);white-space:nowrap"
            >{{ t.value }}</span
          >
          <span
            class="font-mono-fi"
            style="font-size:11px;white-space:nowrap"
            [style.color]="t.up ? 'var(--bn-green)' : 'var(--bn-red)'"
            >{{ t.change }}</span
          >
        </div>
      </div>
    </div>

    <!-- Dock Manager (switches per tab via ngIf + key) -->
    <div style="flex:1;overflow:hidden">
      @for (tab of navTabs; track tab) {
        @if (activeTab() === tab) {
          <dock-manager-core
            [initialState]="getLayout(tab)"
            [widgets]="widgets"
            [theme]="dockTheme"
            (ready)="onDockReady($event)"
          />
        }
      }
    </div>
  `,
  styles: [
    `
      :host {
        display: flex;
        flex-direction: column;
        height: 100vh;
        width: 100vw;
        overflow: hidden;
        background: var(--bn-bg);
      }
    `,
  ],
})
export class App {
  private platformId = inject(PLATFORM_ID);
  private shared = inject(SharedStateService);

  navTabs = NAV_TABS;
  activeTab = signal('Trade');
  isDark = signal(true);
  time = '';
  tickerStrip: TickerItem[] = TICKER_STRIP;
  widgets = WIDGETS;
  dockTheme: DockTheme = slateDark;
  private dockApi: DockviewApi | null = null;
  private clockId: any;

  get isTrading() {
    return this.activeTab() === 'Trade' || this.activeTab() === 'Prices';
  }

  get statsStrip() {
    const bond = this.shared.selectedBond();
    const mid = (bond.bid + bond.ask) / 2;
    const change24h = +(Math.random() * 0.4 - 0.2).toFixed(2);
    const pctChg = +((change24h / mid) * 100).toFixed(2);
    return [
      {
        label: 'Security',
        val: `${bond.ticker} ${bond.cpn.toFixed(3)} ${bond.mat}`,
        color: 'var(--bn-cyan)',
        w: 130,
      },
      {
        label: 'Mid',
        val: mid.toFixed(3),
        color: pctChg >= 0 ? 'var(--bn-green)' : 'var(--bn-red)',
        w: 72,
      },
      { label: 'Bid', val: bond.bid.toFixed(3), color: 'var(--bn-t0)', w: 72 },
      { label: 'Ask', val: bond.ask.toFixed(3), color: 'var(--bn-t0)', w: 72 },
      {
        label: 'Chg',
        val: `${pctChg >= 0 ? '+' : ''}${change24h.toFixed(2)} (${pctChg >= 0 ? '+' : ''}${pctChg.toFixed(2)}%)`,
        color: pctChg >= 0 ? 'var(--bn-green)' : 'var(--bn-red)',
        w: 120,
      },
      {
        label: 'OAS',
        val: bond.oas > 0 ? `+${bond.oas}bp` : '---',
        color: bond.oas > 80 ? 'var(--bn-yellow)' : 'var(--bn-green)',
        w: 52,
      },
      { label: 'Dur', val: `${bond.dur?.toFixed(2) ?? '---'}yr`, color: 'var(--bn-t0)', w: 56 },
    ];
  }

  constructor() {
    effect(() => {
      if (isPlatformBrowser(this.platformId)) {
        const mode = this.isDark() ? 'dark' : 'light';
        document.documentElement.setAttribute('data-theme', mode);
        document.body.dataset['agThemeMode'] = mode;
      }
    });
    effect(() => {
      this.dockTheme = this.isDark() ? slateDark : vsCodeLight;
    });
    // Clock
    const updateClock = () => {
      this.time =
        new Date().toLocaleTimeString('en-US', {
          hour12: false,
          timeZone: 'America/New_York',
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit',
        }) + ' ET';
    };
    updateClock();
    this.clockId = setInterval(updateClock, 1000);
  }

  setActiveTab(t: string) {
    this.activeTab.set(t);
    if (t !== 'Trade') this.shared.showRfq.set(false);
  }

  toggleTheme() {
    this.isDark.update((v) => !v);
  }

  getLayout(tab: string): DockManagerState {
    return (TAB_LAYOUTS[tab] || tradeLayout)();
  }

  onDockReady(api: DockviewApi) {
    this.dockApi = api;
  }

  handleNewOrder() {
    if (!this.dockApi) return;
    if (this.dockApi.hasPanel('tradeTicket')) {
      const gid = this.dockApi.getGroupForPanel('tradeTicket');
      if (gid) this.dockApi.setActivePanel(gid, 'tradeTicket');
      this.dockApi.setActivePane('tradeTicket');
    } else {
      this.dockApi.addPanel({
        id: 'tradeTicket',
        title: 'Trade Ticket',
        widgetType: 'tradeTicket',
        closable: true,
        dockable: false,
      });
      this.dockApi.floatPanel({ panelId: 'tradeTicket', x: 300, y: 80, width: 280, height: 520 });
    }
  }

  handleOpenRfq() {
    if (!this.dockApi) return;
    if (this.dockApi.hasPanel('rfq')) {
      const gid = this.dockApi.getGroupForPanel('rfq');
      if (gid) this.dockApi.setActivePanel(gid, 'rfq');
      this.dockApi.setActivePane('rfq');
      this.dockApi.bringToFront('rfq');
    } else {
      this.dockApi.addPanel({
        id: 'rfq',
        title: 'RFQ Workbench',
        widgetType: 'rfq',
        closable: true,
        dockable: false,
      });
      this.dockApi.floatPanel({ panelId: 'rfq', x: 120, y: 60, width: 720, height: 520 });
    }
  }
}

// packages-import/fi-trading-terminal/react-app/src/App.tsx
import { useState, useCallback, useRef, useMemo } from 'react';
import { DockManagerCore, type WidgetProps, type DockManagerCoreHandle } from '@widgetstools/react-dock-manager';
import { type DockManagerState, slateDark, vsCodeLight } from '@widgetstools/dock-manager-core';
import '@widgetstools/react-dock-manager/styles.css';

import type { Bond, RfqRequest } from '@/data/tradingData';
import { BONDS } from '@/data/tradingData';
import { useTheme } from '@/context/ThemeContext';
import { TopBar } from '@/components/TopBar';
import { CandlestickChart } from '@/components/CandlestickChart';
import { OrderBook } from '@/components/OrderBook';
import { TradeTicket } from '@/components/TradeTicket';
import { BottomOrderPanel } from '@/components/BottomOrderPanel';
import { RfqPanel } from '@/components/RfqSimulator';
import { BondBlotter } from '@/components/BondBlotter';

// Sub-panel components
import { RiskKpiStrip, BookRiskSummary, Dv01Chart, ScenarioChart, VarTrend, RiskLimits } from '@/components/panels/RiskPanels';
import { MarketIndices, EconomicCalendar, IntradayChart, YieldCurvePanel } from '@/components/panels/MarketPanels';
import { OrdersProvider, OrderKpis, OrderBlotter, OrderDetail } from '@/components/panels/OrdersPanels';
import { OasVsDuration, DurationBuckets, SectorAllocation, HistoricalOas, OasDistribution, PnlAttribution } from '@/components/panels/AnalyticsPanels';
import { ResearchProvider, ResearchList, NoteDetail } from '@/components/panels/ResearchPanels';
import { DesignSystemTab } from '@/components/DesignSystemTab';

// ── Shared state ──
interface SharedState {
  selectedBond: Bond;
  setSelectedBond: (b: Bond) => void;
  rfqRequests: RfqRequest[];
  setRfqRequests: React.Dispatch<React.SetStateAction<RfqRequest[]>>;
  showRfq: boolean;
  setShowRfq: (v: boolean) => void;
  clickedPrice: number | undefined;
  setClickedPrice: (p: number | undefined) => void;
}
let _shared: SharedState | null = null;
function getShared(): SharedState { return _shared!; }

// ── Widget wrappers ──
// Trade
function W_Chart(_p: WidgetProps) { const s = getShared(); return <CandlestickChart bond={s.selectedBond} />; }
function W_OrderBook(_p: WidgetProps) { const s = getShared(); return <OrderBook bond={s.selectedBond} onClickPrice={p => s.setClickedPrice(p)} />; }
function W_TradeTicket(_p: WidgetProps) { const s = getShared(); return <TradeTicket bond={s.selectedBond} onSendRfq={() => s.setShowRfq(true)} clickedPrice={s.clickedPrice} />; }
function W_Blotter(_p: WidgetProps) { const s = getShared(); return <BottomOrderPanel bond={s.selectedBond} />; }
function W_Rfq(_p: WidgetProps) { const s = getShared(); return <RfqPanel selectedBond={s.selectedBond} requests={s.rfqRequests} setRequests={s.setRfqRequests} onClose={() => s.setShowRfq(false)} />; }
// Risk
function W_RiskKpi(_p: WidgetProps) { return <RiskKpiStrip />; }
function W_BookRisk(_p: WidgetProps) { return <BookRiskSummary />; }
function W_Dv01(_p: WidgetProps) { return <Dv01Chart />; }
function W_Scenario(_p: WidgetProps) { return <ScenarioChart />; }
function W_Var(_p: WidgetProps) { return <VarTrend />; }
function W_RiskLimits(_p: WidgetProps) { return <RiskLimits />; }
// Market
function W_Indices(_p: WidgetProps) { return <MarketIndices />; }
function W_EconCal(_p: WidgetProps) { return <EconomicCalendar />; }
function W_Intraday(_p: WidgetProps) { return <IntradayChart />; }
function W_YieldCurve(_p: WidgetProps) { return <YieldCurvePanel />; }
// Orders
function W_OrderKpi(_p: WidgetProps) { return <OrderKpis />; }
function W_OrderBlotter(_p: WidgetProps) { return <OrderBlotter />; }
function W_OrderDetail(_p: WidgetProps) { return <OrderDetail />; }
// Analytics
function W_OasDur(_p: WidgetProps) { return <OasVsDuration />; }
function W_DurBuckets(_p: WidgetProps) { return <DurationBuckets />; }
function W_Sectors(_p: WidgetProps) { return <SectorAllocation />; }
function W_HistOas(_p: WidgetProps) { return <HistoricalOas />; }
function W_OasDist(_p: WidgetProps) { return <OasDistribution />; }
function W_Pnl(_p: WidgetProps) { return <PnlAttribution />; }
// Research
function W_ResearchList(_p: WidgetProps) { return <ResearchList />; }
function W_NoteDetail(_p: WidgetProps) { return <NoteDetail />; }
// Prices
function W_BondBlotter(_p: WidgetProps) { const s = getShared(); return <BondBlotter onSelectBond={s.setSelectedBond} />; }
// Design System
function W_DesignSystem(_p: WidgetProps) { return <DesignSystemTab />; }

const WIDGETS: Record<string, React.ComponentType<WidgetProps>> = {
  chart: W_Chart, orderBook: W_OrderBook, tradeTicket: W_TradeTicket, blotter: W_Blotter, rfq: W_Rfq,
  riskKpi: W_RiskKpi, bookRisk: W_BookRisk, dv01: W_Dv01, scenario: W_Scenario, varTrend: W_Var, riskLimits: W_RiskLimits,
  indices: W_Indices, econCal: W_EconCal, intraday: W_Intraday, yieldCurve: W_YieldCurve,
  orderKpi: W_OrderKpi, orderBlotter: W_OrderBlotter, orderDetail: W_OrderDetail,
  oasDur: W_OasDur, durBuckets: W_DurBuckets, sectors: W_Sectors, histOas: W_HistOas, oasDist: W_OasDist, pnl: W_Pnl,
  researchList: W_ResearchList, noteDetail: W_NoteDetail,
  bondBlotter: W_BondBlotter,
  designSystem: W_DesignSystem,
};

// ── Helpers ──
const p = (id: string, title: string, wt: string, closable = false) => ({ id, title, widgetType: wt, closable });
const tg = (id: string, panels: string[], active?: string) => ({ type: 'tabgroup' as const, id, panels, activePanel: active || panels[0] });
const sp = (id: string, dir: 'horizontal' | 'vertical', sizes: number[], children: any[]) => ({ type: 'split' as const, id, direction: dir, sizes, children });
const base = (layout: any, panels: Record<string, any>, active: string): DockManagerState => ({
  layout, panels, floatingPanels: [], popoutPanels: [], unpinnedPanels: [], nextZIndex: 100, activePaneId: active,
});

// ── Per-tab layouts ──

function tradeLayout(): DockManagerState {
  // Layout follows the trading workflow:
  //   Scan (blotter) → Analyze (chart) → Depth (order book) → Monitor (orders)
  //   RFQ + Trade Ticket are floating panels invoked via header buttons
  //
  //  ┌──────────────────┬─────────────────────────┐
  //  │  Bond Blotter     │  Price Chart             │
  //  │  (scan universe)  │  (technical analysis)    │
  //  ├──────────────────┼─────────────────────────┤
  //  │  Order Book       │  Orders                  │
  //  │  (depth/levels)   │  (monitor fills)         │
  //  └──────────────────┴─────────────────────────┘
  return base(
    sp('root', 'vertical', [55, 45], [
      sp('top', 'horizontal', [32, 68], [
        tg('tg-blotter', ['bondBlotter']),
        tg('tg-chart', ['chart']),
      ]),
      sp('bottom', 'horizontal', [32, 68], [
        tg('tg-ob', ['orderBook']),
        tg('tg-orders', ['blotter']),
      ]),
    ]),
    {
      bondBlotter: p('bondBlotter','Bond Blotter','bondBlotter'),
      chart: p('chart','Chart','chart'),
      orderBook: p('orderBook','Order Book','orderBook'),
      blotter: p('blotter','Orders','blotter'),
    },
    'bondBlotter',
  );
}

function pricesLayout(): DockManagerState {
  return base(
    sp('root', 'vertical', [65, 35], [
      tg('tg-blotter', ['bondBlotter']),
      sp('bottom', 'horizontal', [60, 40], [
        tg('tg-chart', ['chart']),
        tg('tg-ob', ['orderBook']),
      ]),
    ]),
    { bondBlotter: p('bondBlotter','Bond Blotter','bondBlotter'), chart: p('chart','Chart','chart'), orderBook: p('orderBook','Order Book','orderBook') },
    'bondBlotter',
  );
}

function riskLayout(): DockManagerState {
  return base(
    sp('root', 'vertical', [12, 88], [
      tg('tg-kpi', ['riskKpi']),
      sp('body', 'horizontal', [25, 50, 25], [
        tg('tg-book', ['bookRisk']),
        sp('charts', 'vertical', [50, 50], [
          sp('charts-top', 'horizontal', [50, 50], [
            tg('tg-dv01', ['dv01']),
            tg('tg-scenario', ['scenario']),
          ]),
          tg('tg-var', ['varTrend']),
        ]),
        tg('tg-limits', ['riskLimits']),
      ]),
    ]),
    { riskKpi: p('riskKpi','Risk KPIs','riskKpi'), bookRisk: p('bookRisk','Book Risk & Heatmap','bookRisk'), dv01: p('dv01','DV01 by Book','dv01'), scenario: p('scenario','Rate Scenarios','scenario'), varTrend: p('varTrend','VaR Trend','varTrend'), riskLimits: p('riskLimits','Risk Limits','riskLimits') },
    'riskKpi',
  );
}

function marketLayout(): DockManagerState {
  return base(
    sp('root', 'horizontal', [30, 70], [
      sp('left', 'vertical', [60, 40], [
        tg('tg-idx', ['indices']),
        tg('tg-cal', ['econCal']),
      ]),
      sp('right', 'vertical', [55, 45], [
        tg('tg-intra', ['intraday']),
        tg('tg-yc', ['yieldCurve']),
      ]),
    ]),
    { indices: p('indices','Market Indices','indices'), econCal: p('econCal','Economic Calendar','econCal'), intraday: p('intraday','Intraday Chart','intraday'), yieldCurve: p('yieldCurve','Yield Curve','yieldCurve') },
    'indices',
  );
}

function ordersLayout(): DockManagerState {
  return base(
    sp('root', 'vertical', [12, 88], [
      tg('tg-kpi', ['orderKpi']),
      sp('body', 'horizontal', [75, 25], [
        tg('tg-blot', ['orderBlotter']),
        tg('tg-det', ['orderDetail']),
      ]),
    ]),
    { orderKpi: p('orderKpi','Order KPIs','orderKpi'), orderBlotter: p('orderBlotter','Order Blotter','orderBlotter'), orderDetail: p('orderDetail','Order Detail','orderDetail') },
    'orderBlotter',
  );
}

function analyticsLayout(): DockManagerState {
  return base(
    sp('root', 'vertical', [50, 50], [
      sp('row1', 'horizontal', [34, 33, 33], [
        tg('tg-oas', ['oasDur']),
        tg('tg-dur', ['durBuckets']),
        tg('tg-sec', ['sectors']),
      ]),
      sp('row2', 'horizontal', [34, 33, 33], [
        tg('tg-hist', ['histOas']),
        tg('tg-dist', ['oasDist']),
        tg('tg-pnl', ['pnl']),
      ]),
    ]),
    { oasDur: p('oasDur','OAS vs Duration','oasDur'), durBuckets: p('durBuckets','Duration Buckets','durBuckets'), sectors: p('sectors','Sector Allocation','sectors'), histOas: p('histOas','CDX IG/HY Historical','histOas'), oasDist: p('oasDist','OAS Distribution','oasDist'), pnl: p('pnl','P&L Attribution','pnl') },
    'oasDur',
  );
}

function researchLayout(): DockManagerState {
  return base(
    sp('root', 'horizontal', [30, 70], [
      tg('tg-list', ['researchList']),
      tg('tg-detail', ['noteDetail']),
    ]),
    { researchList: p('researchList','Research Notes','researchList'), noteDetail: p('noteDetail','Note Detail','noteDetail') },
    'researchList',
  );
}

function designSystemLayout(): DockManagerState {
  return base(
    tg('tg-ds', ['designSystem']),
    { designSystem: p('designSystem', 'Design System', 'designSystem') },
    'designSystem',
  );
}

const TAB_LAYOUTS: Record<string, () => DockManagerState> = {
  Trade: tradeLayout, Prices: pricesLayout,
  Risk: riskLayout, Market: marketLayout,
  Research: researchLayout, Orders: ordersLayout,
  Analytics: analyticsLayout, 'Design System': designSystemLayout,
};

// ── Tabs that need context providers wrapping the dock manager ──
function PassThrough({ children }: { children: React.ReactNode }) { return <>{children}</>; }

const TAB_WRAPPERS: Record<string, React.ComponentType<{children: React.ReactNode}>> = {
  Trade: PassThrough,
  Prices: PassThrough,
  Risk: PassThrough,
  Market: PassThrough,
  Orders: OrdersProvider,
  Research: ResearchProvider,
  Analytics: PassThrough,
  'Design System': PassThrough,
};

export default function App() {
  const { isDark } = useTheme();
  const [activeTab, setActiveTab] = useState('Trade');
  const [selectedBond, setSelectedBond] = useState<Bond>(BONDS[0]);
  const [rfqRequests, setRfqRequests] = useState<RfqRequest[]>([]);
  const [showRfq, setShowRfq] = useState(false);
  const [clickedPrice, setClickedPrice] = useState<number | undefined>();
  const dockRef = useRef<DockManagerCoreHandle>(null);

  _shared = { selectedBond, setSelectedBond, rfqRequests, setRfqRequests, showRfq, setShowRfq, clickedPrice, setClickedPrice };

  const handleTabChange = useCallback((t: string) => { setActiveTab(t); if (t !== 'Trade') setShowRfq(false); }, []);

  const handleNewOrder = useCallback(() => {
    const api = dockRef.current?.getApi();
    if (!api) return;
    if (api.hasPanel('tradeTicket')) {
      const gid = api.getGroupForPanel('tradeTicket');
      if (gid) api.setActivePanel(gid, 'tradeTicket');
      api.setActivePane('tradeTicket');
    } else {
      api.addPanel({ id: 'tradeTicket', title: 'Trade Ticket', widgetType: 'tradeTicket', closable: true, dockable: false });
      api.floatPanel({ panelId: 'tradeTicket', x: 300, y: 80, width: 280, height: 520 });
    }
  }, []);

  const handleOpenRfq = useCallback(() => {
    const api = dockRef.current?.getApi();
    if (!api) return;
    if (api.hasPanel('rfq')) {
      const gid = api.getGroupForPanel('rfq');
      if (gid) api.setActivePanel(gid, 'rfq');
      api.setActivePane('rfq');
      api.bringToFront('rfq');
    } else {
      api.addPanel({ id: 'rfq', title: 'RFQ Workbench', widgetType: 'rfq', closable: true, dockable: false });
      api.floatPanel({ panelId: 'rfq', x: 120, y: 60, width: 720, height: 520 });
    }
  }, []);

  const currentLayout = useMemo(() => (TAB_LAYOUTS[activeTab] || tradeLayout)(), [activeTab]);
  const dockTheme = isDark ? slateDark : vsCodeLight;
  const Wrapper = TAB_WRAPPERS[activeTab] || PassThrough;
  const isTrading = activeTab === 'Trade' || activeTab === 'Prices';

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', width: '100%', overflow: 'hidden', background: 'var(--bn-bg)' }}>
      <TopBar activeTab={activeTab} onTabChange={handleTabChange} selectedBond={selectedBond} onNewOrder={isTrading ? handleNewOrder : undefined} onOpenRfq={isTrading ? handleOpenRfq : undefined} />
      <Wrapper>
        <div className="dock-manager-container" style={{ flex: 1, overflow: 'hidden' }}>
          <DockManagerCore key={activeTab} ref={dockRef} initialState={currentLayout} widgets={WIDGETS} theme={dockTheme} />
        </div>
      </Wrapper>
    </div>
  );
}
